live_config_reload = true

[cursor]
style = "Beam"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 1000

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
dynamic_padding = true
opacity = 1

[window.padding]
x = 0
y = 0
